from astropy.io import fits
import numpy as np
import re

def cast_hdudata_to_numpy(hdu_list_data, start = 0, end = 20, exclude = 0):
    '''
    casts a HDU_List_data generated by Astropy to a numpy array
    :param hdu_list: , start:0, end:0
    :return: numpy array
    '''

    num_rows = hdu_list_data.field(0).size      #include check if all rows are filled
    '''Generate empty Numpy Matrix'''
    np_data = np.empty([end-start, num_rows])
    for n in range(start, end):
        for m in range(0, num_rows):
            np_data[n][m] = hdu_list_data.field(n)[m]
    print(np_data)



if __name__ == '__main__':
    hdulist = fits.open('/home/maxi/data/y1a1_stripe82_train_subset.fits')
    dt = ['float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','float16','char','int64','char','int64','int','char','char','float16','float16','float16','float16','float16','float16']
    numpy_list = np.fromfile('/home/maxi/data/y1a1_stripe82_train_subset.fits', dtype=dt)

    print(numpy_list[5])
    info = str(repr(hdulist[1].header))
    print(info)
    info = re.sub(r'\s+', '', info)
    print(info)
    x = 1
    y=0
    typed = 'we found'
    while y != -1 and x < len(info)-20:
        y = info.find('TFORM'+str(x))
        x=x+1
        print(x)
        if (x > 10):
            print(info[y:y+12])
            typed = typed + ' ' + info[y+9]
        else:
            print(info[y:y+12])
            typed = typed + ' ' + info[y+8]
    print(typed)

    typed = typed.replace('D', '\'float16\'')
    typed = typed.replace('2', '\'char\'')
    typed = typed.replace('K', '\'int64\'')
    typed = typed.replace('I', '\'int\'')
    typed = typed.replace(" ",",")
    print(typed)


    #data  = hdulist[1].data
    #cast_hdudata_to_numpy(data)
